---
title: "Methods Exploration: Phylogenetics in R"
author: "John Hinkle"
format: html
editor: visual
self-contained: true
---

## Load packages

```{r}
library(adegenet)
library(ggtree)
library(ggimage)
```

## Load FASTA file

This contains sequence data in FASTA format

```{r}
seqs <- fasta2DNAbin("./data/usflu.fasta")
```

## Load annotation data

```{r}
library(tidyverse)
a <- read_csv("./data/usflu.annot.csv")
head(a)
```

## Wrangle annotation data

```{r}
a <- a |>
  mutate(state = str_extract(misc, "(?<=/)[^/]+(?=/)")) |>
  mutate(state = ifelse(state == "Memphis", "Tennessee", state))
head(a)
```

## Pairwise distances

```{r}
library(ape)
dist <- dist.dna(seqs, model = "K80")
```

## Create tree object

```{r}
# Neighbor-Joining 2.0
t <- bionj(dist)

# Neighbor-Joining
# Maximum Likelihood
# Minimum Evolution
```

## Plot tree

```{r}
# open tree in new window for optimal viewing
ggtree(t) +
  geom_tiplab()
```

## Add annotation data to the tree

```{r}
p <- ggtree(t) %<+% a
```

## Add color to trees

```{r}
library(viridis)
p + geom_tiplab(aes(color = year)) +
    scale_color_viridis_c() +
    theme_tree2()
```

```{r}
p + geom_tiplab(aes(color = state)) +
    scale_color_hue(n = 15) +
    theme_tree2()
```

## Annotating branches with state flags

```{r}
glimpse(a)
```

```{r}
us_state_flag_tree <- function(tree, metadata, image_column = "image_path", label_column = "label") {

  # create ggtree object from tree object
  p <- ggtree(tree)

  # extract tree data and join with metadata
  tree_data <- p$data
  tip_data <- tree_data |>
    filter(isTip) |>
    left_join(metadata, by = setNames(label_column, "label"))

  # create "offset" to space flag icons at end of tip label, to prevent overlap
  offset <- max(tree_data$x, na.rm = TRUE) * 0.085

  # create ggtree plot
  p +
    geom_image(
      data = tip_data,
      aes(x = x + offset, y = y, image = .data[[image_column]]),
      size = 0.025, asp = 1.0
    ) +
    geom_tiplab()
}

us_state_flag_tree(t, a, image_column = "ImagePath", label_column = "accession")
```
